### PR TITLE
Migrate APIs.guru URL to specs

### PR DESCRIPTION
**Pull request by IvanGoncharov**
More details here: https://github.com/APIs-guru/api-models/issues/85
Change is very simple.

@shaharsol Can you please review it?

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@shaharsol Can you please review it?
It blocks migration to API v2.

**Comment by shaharsol** [comment]
@IvanGoncharov sure, I hope to get to this soon.

**Comment by IvanGoncharov** [comment]
@shaharsol This is one line change. Can you please review it?

**Comment by IvanGoncharov** [comment]
@shaharsol Can you please review this PR?

**Comment by shaharsol** [comment]
@IvanGoncharov sorry it took so long. pls bare in mind though that ppl will still have this in their local installations until (if they ever) upgrade. How long do you intend to support the old url structure?

**Comment by IvanGoncharov** [comment]
No problem.

> pls bare in mind though that ppl will still have this in their local installations until (if they ever) upgrade.

Yes but it doesn't affect already installed spec only new ones.
So I don't think it so critical.

> How long do you intend to support the old url structure?

We supported old one for more than two months and switched it off couple weeks ago.
It was required in order to fix redirection problems with `apis.guru` domain.

**Pull request merged**
